### PR TITLE
Add simple ELK sample

### PR DESCRIPTION
**Pull request by s-hosoai**
Hi Arnaud,

I created a simple ELK sample. This is an experimental implementation and skips any check.
The node and edge layout is working. However, the label does not seem to contribute to the layout.
Maybe it needs to calculate the boundaries.

I hope that the PlantUML layout will be more convenient!

### CODE REVIEW

**Comment by arnaudroques** [comment]
Thanks to your contribution, we have started to link PlantUML and ELK.

If you [retrieve last committed version](https://github.com/plantuml/plantuml) and build it with maven, you could try :

```
@startuml
!pragma graphviz_dot elk
class foo1
class foo2
class foo3

foo1 --> foo2
foo1 --> foo3
@enduml
```

Ok, the result is not that good.
We are not sure how to use ELK actually.

However, since this is now integrated with PlantUML, you can have a look at:
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/elk/CucaDiagramFileMakerElk.java

Our first goal is to have a first version with nodes only.
As you can see, nodes are not correctly positioned.
There is probably something wrong we are doing in https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/elk/CucaDiagramFileMakerElk.java#L168

Patching CucaDiagramFileMakerElk.java should not be very difficut, but we need help now.
Thanks!

**Comment by hallvard** [comment]
It seems you need to set the label text, otherwise it won't consider its dimensions. I added `int num = 1` above the loop and `label.setText("node " + num++);` just after its creation and got
```
node node : 12.0, 21.666666666666664 (68.0, 58.0)
node node : 100.0, 12.0 (68.0, 58.0)
node node : 100.0, 90.0 (68.0, 58.0)
```
I seem to automatically get 10 points padding, even though I try to set it to 2...
Now if you could just render the edges, too!

**Comment by hallvard** [comment]
BTW, some tests failed when running `mvn install` so I use `Debug As > Java Application` on the `Run` class and watch a test folder. Here's a sample 
Screenshot 2021-04-14 at 00 14 59

**Comment by arnaudroques** [comment]
> Now if you could just render the edges, too!

It's done !

We try to have the simplest code right now, so people can help us. Edges drawing is done [here](https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/elk/ElkPath.java). 

> BTW, some tests failed when running `mvn install`

Could you tell us more about this ? It's running fine for us.


There is still a lot of work to be done:

- We don't know how to handle "package" (that is "cluster" in GraphViz) with ELK. (see for [example](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIf8JCvEJ4zLIClFLwZcIiv9B2vM09E6o1mZhbekkDAan29KfSR871EGKeW92hgwTZ0L3gbvAK3x0000))

- Edge labels are nor drawn nor taken into [account in ELK layout](http://www.plantuml.com/plantuml/uml/JOqn2iD030JxUyL-m4tA5C4FSIFRIcpGIU6a2zpleq0ALpiBm-xiGIrwbR89kUDfzgULMic6QNhy67V4SJg4LXOaVBYDHSNq1T8T1tacplgcBHOrJPtJ7jRZkdChC-kUXry0).
- By default, GraphViz is top to bottom oriented. It seems that ELK is left to right oriented. Any idea on how to change this ?

Thanks again!

**Comment by hallvard** [comment]
I see the edges now!

After changing the loop where you add edges to

```
			for (final Link link : diagram.getLinks()) {
				final ElkEdge edge = ElkGraphUtil.createEdge(root);
				final Display label = link.getLabel();
				if (label.size() > 0) {
					final String s = label.get(0).toString();
					final ElkLabel edgeLabel = ElkGraphUtil.createLabel(edge);
					edgeLabel.setText(s);
					edgeLabel.setDimensions(40, 20);
					edge.setProperty(CoreOptions.EDGE_LABELS_INLINE, true);
					edge.setProperty(CoreOptions.EDGE_TYPE, EdgeType.ASSOCIATION);
				}
				edge.getSources().add(nodes.get(link.getEntity1()));
				edge.getTargets().add(nodes.get(link.getEntity2()));
				edges.put(link, edge);
			}

```
there's more space between the nodes for the edge labels (the dimensions are fixed, as you see). It would be nice if you could also represent the real labels as ELK labels with correct dimensions and then render them afterwards. Then it's easier to play with the layout parameters.

Concerning clusters, ELK nodes can be root or interior nodes in a tree/graph, so you can just use generic nodes, I guess.

Concerning layout direction, set a property of the graph at the top, as follows
```
root.setProperty(CoreOptions.DIRECTION, Direction.DOWN);
```

Should we perhaps move this discussion to an ELK issue?

Concerning the tests, this is from one of 7 test failures:
```
[ERROR]   A0006_Test.testSimple:51->BasicTest.checkImage:55 expected: <DPI: 96
```
The others seemed similar.

**Comment by arnaudroques** [comment]
> Should we perhaps move this discussion to an ELK issue?
> 

Right, we've just [opened this one](https://github.com/plantuml/plantuml/issues/534).

> Concerning the tests, this is from one of 7 test failures:
> 
> ```
> [ERROR]   A0006_Test.testSimple:51->BasicTest.checkImage:55 expected: <DPI: 96
> ```
> 
> The others seemed similar.

Ok, thanks. We have to look after this. It seems to work [here](https://github.com/plantuml/plantuml/runs/2354955537?check_suite_focus=true) but we probably have to enhance the error message.

**Pull request merged**
